### ISSUE TITLE
Edit note

### ISSUE THREAD

**Issue by manuelbertelli** [kawamanza/step-up#33]
I'd like to edit an existing note. Nowadays we can't do that.

Suggested command:
stepup notes edit <SHA1>

Suggested internal flow:
1) Open default editor with the message of the note
2) When user closes the editor, remove the old note and add a new one with the new content.

**Comment by dgmike** [comment]
Recentely I discover there's a way to create stepup notes, using the commit message and prefix listed on `.stepuprc` file.

So... take a look.

```yaml
# .stepuprc
  sections:
    - name: "changes"
      prefix: "change: " # this is the magical prefix
      label: "Changes:"
      tag: "change"
```

And here is the commit message:

```bash
git commit -m "change: create users requires age attribute"
```

`stepup` uses commit messages and ref notes to rescue versioning notes.

```bash
$ stepup notes
---
Changes:

  - create users requires age attribute
```

This is a great way to create version notes. And is extremely easy to edit notes... above some examples...

```bash
$ git commit --amend
$ git rebase -i HEAD~5
```

Ammend documentation: https://git-scm.com/docs/git-commit#git-commit---amend
Rebase documentation: https://git-scm.com/docs/git-rebase
Git Tools - Rewriting History: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
